export const ActionTypes = {
    SET_COUNTRIES : 'SET_COUNTRIES',
    SELECT_COUNTRIES : 'SELECT_COUNTRIES',
    SEARCH_COUNTRIES : 'SEARCH_COUNTRIES',
    REMOVE_SELECT_COUNTRIES : 'REMOVE_SELECT_COUNTRIES',
};

